# Generated by Django 4.1.7 on 2023-03-27 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='housekeep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 3, 27, 13, 55, 33, 361748, tzinfo=datetime.timezone.utc))),
                ('category', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
