# Generated by Django 4.1.7 on 2023-04-09 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeep',
            name='category',
            field=models.CharField(blank=True, choices=[('Grocery', 'Grocery'), ('Restaurant', 'Restaurant'), ('Internet', 'Internet'), ('Fashion', 'Fashion'), ('Study', 'Study'), ('Medical', 'Medical'), ('Subscription', 'Subscription'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='housekeep',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 9, 13, 49, 26, 345646, tzinfo=datetime.timezone.utc)),
        ),
    ]
